/**
 * Created by Mitaka on 01-Aug-18.
 */
import React from 'react';

const TestContent = () =>
    <div>
        {window.innerWidth}
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
            Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
        Temporary Test Main Content
    </div>;

export default TestContent;